apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.controller.configAnnotations }}
  annotations: {{ toYaml .Values.controller.configAnnotations | nindent 4 }}
{{- end }}
  name: {{ include "ingress-nginx.controller.fullname" . }}.otel
  namespace: {{ .Release.Namespace }}
data:
    otel-nginx.toml: |
      exporter = "otlp"
      processor = "batch"
      [exporters.otlp]
      # Alternatively the OTEL_EXPORTER_OTLP_ENDPOINT environment variable can also be used.
      host = "otel-coll-collector.otel.svc"
      port = 4317

      [processors.batch]
      max_queue_size = 2048
      schedule_delay_millis = 5000
      max_export_batch_size = 512

      [service]
      name = "nginx-proxy" # Opentelemetry resource name

      [sampler]
      name = "AlwaysOn" # Also: AlwaysOff, TraceIdRatioBased
      ratio = 1.0
      parent_based = false

      #exporter = \"otlp\"\nprocessor = \"batch\"\n\n[exporters.otlp]\n# Alternatively the OTEL_EXPORTER_OTLP_ENDPOINT environment variable can also be used.\nhost = \"otel-coll-collector.otel.svc\"\nport = 4317\n\n[processors.batch]\nmax_queue_size = 2048\nschedule_delay_millis = 5000\nmax_export_batch_size = 512\n\n[service]\nname = \"nginx-proxy\" # Opentelemetry resource name\n\n[sampler]\nname = \"AlwaysOn\" # Also: AlwaysOff, TraceIdRatioBased\nratio = 1.0\nparent_based = false\n"
