name: Container Images

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'images/**'

  push:
    branches:
      - main
    paths:
      - 'images/**'

permissions:
  contents: write
  packages: write

env:
  PLATFORMS: linux/amd64

jobs:

  nginx:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          version: latest
          platforms: ${{ env.PLATFORMS }}
      - name: build-image
        run: |
          export TAG=$(cat images/nginx/TAG)
          cd images/nginx/rootfs && docker buildx build --platform=${{ env.PLATFORMS }} -t ingressnginx/nginx:${TAG} .
